### ISSUE TITLE
Module not working after last update

### ISSUE THREAD

**Issue by DintyGadget** [VORPCORE/VORP-Character#14]
If you build the project with the latest update. Nothing happens when I log in to the server. The player spawns as Arthur and does not get into the editor. At the same time, the console of both the client and the server does not show errors in the script or its initiation.

**Comment by Local9** [comment]
[Built against repo: vorp_character.zip](https://github.com/VORPCORE/VORP-Character/files/8010248/vorp_character.zip)

Current files from my own, this runs against the premade else the files below are the older resource;

[OLD: vorp_character.zip](https://github.com/VORPCORE/VORP-Character/files/8010253/vorp_character.zip)

**Comment by Local9** [comment]
closing due to new release
