### ISSUE TITLE
Character Editor/Loader

### ISSUE THREAD

**Issue by GalatheasUncharted** [VORPCORE/VORP-Character#15]
Issue from Discord:
When it happens
Everytime at Charselection / Whole time ingame
 
Name of the script
Not shure: Core or Character

Onesync?
Yes

What were you doing?
Hands and Boots dosnt shown. Hands are invisible and Boots not shown.
If i go to a clothshop (vorp_clotheshop) and buy new boots, they will shown.
If i use the F6 radial menu (rm) to toogle the boots... i can take them off, but not take them on.

------
Additions:
A new Created Character dosnt looks the same, as i do it in Character Creator. Eg.
I made a Indian Character with a darker skin color, wide nose and so on with much aging and stuff like that.
And the Character looks after login totaly different...

I'll create shortly a new Character and notice alle values, and check the values in database...
May the Save to Database function is broken? (pls let me verify first)

**Comment by Local9** [comment]
Possible some items not being stored/pulled correctly. I've been busy with core refactor hense releasing this as it is currently with minor issues.
