### ISSUE TITLE
Unhandled Task execption

### ISSUE THREAD

**Issue by Zaickz** [VORPCORE/VORP-Character#16]
- On Character spawn this error shows up
- ![problem](https://user-images.githubusercontent.com/3839603/153757679-35370372-955a-4533-8d39-dc9f5a608b45.JPG)

- FXServer Build 5327
- RedM Client Build ver 5318/Beta but on release its the same error
-skinPlayer:
`{
  "sex": "mp_male",
  "HeadType": 0,
  "BodyType": 0,
  "LegsType": 0,
  "HeadSize": 0.0,
  "EyeBrowH": 0.0,
  "EyeBrowW": 0.0,
  "EyeBrowD": 0.0,
  "EarsH": 0.0,
  "EarsW": 0.0,
  "EarsD": 0.0,
  "EarsL": 0.0,
  "EyeLidH": 0.0,
  "EyeLidW": 0.0,
  "EyeD": 0.0,
  "EyeAng": 0.0,
  "EyeDis": 0.0,
  "EyeH": 0.0,
  "NoseW": 0.0,
  "NoseS": 0.0,
  "NoseH": 0.0,
  "NoseAng": 0.0,
  "NoseC": 0.0,
  "NoseDis": 0.0,
  "CheekBonesH": 0.0,
  "CheekBonesW": 0.0,
  "CheekBonesD": 0.0,
  "MouthW": 0.0,
  "MouthD": 0.0,
  "MouthX": 0.0,
  "MouthY": 0.0,
  "ULiphH": 0.0,
  "ULiphW": 0.0,
  "ULiphD": 0.0,
  "LLiphH": 0.0,
  "LLiphW": 0.0,
  "LLiphD": 0.0,
  "JawH": 0.0,
  "JawW": 0.0,
  "JawD": 0.0,
  "ChinH": 0.0,
  "ChinW": 0.0,
  "ChinD": 0.0,
  "Beard": 1858638465,
  "Hair": 2874852206,
  "Body": 0,
  "Waist": 0,
  "Eyes": 0,
  "Scale": 0.75,
  "eyebrows_visibility": 0,
  "eyebrows_tx_id": 0,
  "scars_visibility": 0,
  "scars_tx_id": 0,
  "spots_visibility": 0,
  "spots_tx_id": 0,
  "disc_visibility": 0,
  "disc_tx_id": 0,
  "complex_visibility": 0,
  "complex_tx_id": 0,
  "acne_visibility": 0,
  "acne_tx_id": 0,
  "ageing_visibility": 0,
  "ageing_tx_id": 0,
  "freckles_visibility": 0,
  "freckles_tx_id": 0,
  "moles_visibility": 0,
  "moles_tx_id": 0,
  "grime_visibility": 0,
  "grime_tx_id": 0,
  "lipsticks_visibility": 0,
  "lipsticks_tx_id": 0,
  "lipsticks_palette_id": 0,
  "lipsticks_palette_color_primary": 0,
  "shadows_visibility": 0,
  "shadows_tx_id": 0,
  "shadows_palette_id": 0,
  "shadows_palette_color_primary": 0,
  "albedo": 317354806
}`
- compPlayer:
`{"Hat":-1,"Mask":4294967295,"EyeWear":-1,"NeckWear":-1,"NeckTies":-1,"Shirt":1478455338,"Suspender":-1,"Vest":-1,"Coat":4294967295,"Poncho":4294967295,"Cloak":4294967295,"Glove":4294967295,"RingRh":3742761105,"RingLh":3403528701,"Bracelet":-1,"Gunbelt":4294967295,"Belt":4294967295,"Buckle":4294967295,"Holster":4294967295,"Pant":3264198958,"Skirt":-1,"Chap":-1,"Boots":3485986228,"Spurs":4294967295,"Spats":4294967295,"Gauntlets":-1,"Loadouts":-1,"Accessories":-1,"Satchels":-1,"GunbeltAccs":4294967295,"CoatClosed":4294967295}`

**Comment by Local9** [comment]
Known issue in the previous version before the refactor.
