### ISSUE TITLE
SetPlayerComponents - LoadPlayer.cs

### ISSUE THREAD

**Issue by ScouseMouse21** [VORPCORE/VORP-Character#18]
Found this while trying to figure out why "bow", "armor", "teeth" wasn't saving / spawning as intended 

`ePedComponent.Skirt` is listed for bow, armor, teeth.

![bug](https://user-images.githubusercontent.com/40149867/156364842-33e57231-6557-48fe-9b5d-56afc292d565.png)

**Comment by Local9** [comment]
This issue has now been fixed
