### ISSUE TITLE
Gunbelt accessories bug

### ISSUE THREAD

**Issue by Scheggia0** [VORPCORE/VORP-Character#20]
During character creation the Gunbelt Accessories option has the same clothing as the Satchels option, as seen in both attached screenshots.

![Immagine 2022-03-14 153125](https://user-images.githubusercontent.com/68442046/158194341-f6734ec8-a7c7-4181-b880-d2e3f4c44881.png)
![Immagine 2022-03-14 153154](https://user-images.githubusercontent.com/68442046/158194347-4f17fe57-2b7f-4a85-885e-62a1cc3ef6c7.png)

**Comment by Local9** [comment]
closed https://github.com/VORPCORE/VORP-Character/commit/c2d98b2adb8b25b22ec79ba00b0d09350cd0fd8f
