### ISSUE TITLE
Arthur Spawn

### ISSUE THREAD

**Issue by Skeez-ARP** [VORPCORE/VORP-Character#25]
Upon load in, it will not move into character creation/selection. It leaves you spawned in as Arthur and you can run around the cabin. This is after updating to your latest version with the fixes mentioned above. Using this version https://github.com/VORPCORE/VORP-Character/releases/tag/v1.0.1

![image](https://user-images.githubusercontent.com/57041193/160248520-496f54bf-3e0c-4304-9566-18e427934612.png)

**Comment by Local9** [comment]
Every test I've done, I've been unable to replicate, so please provide a video.

**Comment by Skeez-ARP** [comment]
No problem, I have attached the video link below. We reverted back to the version before your recent changes and the issue stops.

https://drive.google.com/file/d/1UMcVVKi-61Bb4IMuxN7C9ZFlrxdO-sBp/view?usp=sharing

**Comment by Local9** [comment]
[vorpcharacter_cl.net.zip](https://github.com/VORPCORE/VORP-Character/files/8355904/vorpcharacter_cl.net.zip)

I'm still unable to replicate the issue using the premade server files, I have how ever added back in an old event that I couldn't find being used any where in my refactoring, so please try the client file attached.

**Comment by Skeez-ARP** [comment]
Replaced with that client file, but the issue still persists. I tried clearing the vorp_character from cache as well just in case, but it is still happening. Reverting back to the attached version is working fine.

https://drive.google.com/file/d/11bnF8K6HN57f73NCN-ayZg1sqol6FU1h/view?usp=sharing

**Comment by Local9** [comment]
Ok, so the issue is to do with actions you did, not that you're just spawning as Arthur, which is how the issue came across. I'll try now myself to replicate by deleting the characters I have in testing to see if the same issue can be replicated.

**Comment by Skeez-ARP** [comment]
Yes, you are correct and that is my fault for not clarifying the actions. I will try to be more thorough in future issue posts.

**Comment by Local9** [comment]
Ok the issue is that vorp-core-lua doesn't match the original vorp-core when it comes to character selection/creation, will have to look at older code and see if that does something different.

**Comment by Local9** [comment]
Found it, really hate the event calls in this entire process, should hopefully have it fixed soon.

**Comment by Local9** [comment]
https://github.com/VORPCORE/VORP-Character/releases/tag/v1.0.1-hotfix.2

Should fix it

**Comment by Skeez-ARP** [comment]
That fixed the issue for sure. I was able to create two, delete both and then create another. The only thing I noticed is that the body color will not change. I can open a new issue for that if you want?

**Comment by Local9** [comment]
Its an issue I'm aware of, but as most of this is trying to fix something thats a [big ball of mud](https://en.wikipedia.org/wiki/Big_ball_of_mud) I've stayed away from most of the character creator while writing a new one into the C# VORP-CORE refactor. Current progress on that can be [seen here](https://youtu.be/153W1YmDkQc)

**Comment by Skeez-ARP** [comment]
Sounds good. I appreciate your time and effort. The new one looks great, can't wait for the release. Really clean!
