### ISSUE TITLE
Delete Hold Time to Short

### ISSUE THREAD

**Issue by BulletJRP** [VORPCORE/VORP-Character#30]
On character select screen there is no prompt to press escape. Players press escape and hold for one second, their character is deleted. 

VORP-Character/VORP-Character[Client-Server]/vorpcharacter_cl/Script/SelectCharacter.cs
L: 105
API.PromptSetHoldMode(DeletePrompt, 1);

Need this hold time changed to 10 seconds or more.

**Comment by Local9** [comment]
This would be in the November build? because the refactor uses confirmation dialog.

**Comment by BulletJRP** [comment]
A confirmation dialogue exists. Thank you.
