### ISSUE TITLE
Player comp replaced with SQL Query

### ISSUE THREAD

**Issue by LtDoc** [VORPCORE/VORP-Character#32]
The compPlayer column will randomly replace the standard composition with an SQL query in individual rows which prevents players from selecting a character. They get stuck on the selection screen and no character shows up. The current workaround is to just apply another character's comp or a comp from a DB backup and then the user can load in and change their clothing. 

Don't have a current example in my DB but the query as far as I can remember is an inventory update. Will update this issue if I get it again so hopefully it can help isolate the issue.

**Comment by Local9** [comment]
This is an issue with vorp-core-lua; I recommend opening the issue there. https://github.com/VORPCORE/vorp-core-lua

**Comment by kamelzarandah** [comment]
ive had the same problem, so i can confirm its happening to big servers. it seems to be random

**Comment by Local9** [comment]
Because the issue has only been happening since vorp-core-lua was introduced, I'm unaware of the issue predating that resoure.

**Comment by LtDoc** [comment]
> Because the issue has only been happening since vorp-core-lua was introduced, I'm unaware of the issue predating that resoure so its not something this resource can correct without changing the character handling.

I can definitely confirm we had this issue prior to vorp-core-lua introduction. This has been an issue since I started my server in December. Same issue happens in multiple columns. I actually am going to [attach an image](https://i.gyazo.com/8bc55f9cc333fa71de10e249cf7b09fd.png) of the insertion. I don't know about other servers but I never reported the issue because I didn't see any other servers reporting and assumed it was something we had done on our end.

**Comment by Local9** [comment]
Ok, but, we have another issue, because that example isn't something that this resource can produce, as that SQL query isn't even in this resource. This points more towards bad MySQL resource, or bad use of it. The only SQL ran by this resource is when `vorp_updateexisting` is ran, that only changes firstname, lastname, skinPlayer, and compPlayer.
