### ISSUE TITLE
Problem with the skirt / pants

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Character#4]
There is a problem with skirt:
/reloadcloths - Is not solving this 

Pants are set to 0 in creator.

![unknown](https://user-images.githubusercontent.com/69915160/96800298-46ca7f00-1405-11eb-943f-b8814c9d3c32.png)
problem.

**Comment by NeoGaming22** [comment]
I can confirm this we are also having same issue

**Comment by DintyGadget** [comment]
I managed to find a solution to this problem! 

(Relevant for the version of June 31, 2021  https://github.com/VORPCORE/VORP-Character/tree/a47f85a4de0eab3651da31745b39393f55bb11a3)

You need to add a second function, in ApplyDefaultSkinCanaryEdition
```
Function.Call((Hash)0xD710A5007C2AC539, ped, 0x3F1F01E5, 0); // After this line
Function.Call((Hash)0xD710A5007C2AC539, API.PlayerPedId(), 0x1D4C528A, 0); // Need to add to both male and female model
```
Pants will not appear on the model, and therefore will not appear if you are wearing a skirt and no pants. However, the models that appear on the character creation screen will be completely naked. To solve this problem, you need to add clothing to both the male and female models.

Male (prison suit)
```
// Dress Ped
Function.Call((Hash)0xD3A7B003ED343FD9, ped, 0x216612F0, true, true, false);
Function.Call((Hash)0xD3A7B003ED343FD9, ped, 0x5BA76CCF, true, true, false);
```
Female (prison suit)
```
// Dress Ped
Function.Call((Hash)0xD3A7B003ED343FD9, ped, 0x75BC0CF5, true, true, false);
Function.Call((Hash)0xD3A7B003ED343FD9, ped, 0x6AB27695, true, true, false);
```

**Comment by outsider31000** [comment]
why not make a pull request @DintyGadget  i have just seen this

**Comment by Local9** [comment]
This is already patched in the current code, I have how ever updated the ordering; https://github.com/VORPCORE/VORP-Character/commit/39aa9c0848580146cc6428af0458e4388f986b68

Issue with naked peds is being investigated in https://github.com/VORPCORE/VORP-Character/issues/22
