### ISSUE TITLE
Loading as arthur

### ISSUE THREAD

**Issue by ZioMark13** [VORPCORE/VORP-Character#46]
I make the character and all works, when i relog i spawn as arthur morgan... i see money and everything but i cannot move from the default spawn hut

**Comment by Domwell** [comment]
Same problem.

**Comment by outsider31000** [comment]
Use premade

**Comment by GDLSstudios** [comment]
I'm having this issue except I'm not even getting the chance to create a character at all, it immediately spawns me in as either John or Arthur and I know I have it ensured in the .cfg, is there something I am missing, I am new to this and just learning. I started with the premade vorp available if that helps.

**Comment by BluePie31** [comment]
has anyone found a solution yet?

**Comment by outsider31000** [comment]
The issue isnt with the script but how you load them and missing updates on your end.
