### ISSUE TITLE
The place where you choose your character Problems.

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Character#7]
In the place where we choose the character, Arthur appears to random players and the door is opening when someone joins...
![Bez tytułu](https://user-images.githubusercontent.com/69915160/98560967-a1d6ef80-22a8-11eb-9334-cc553fbcb003.png)
![Bez tytułu1](https://user-images.githubusercontent.com/69915160/98560971-a3081c80-22a8-11eb-8b86-736f261a6ba0.png)

**Comment by Local9** [comment]
This I wouldn't say is an issue, but is more a desirable change. Changing the character creation process and selection to use Routing Buckets will get around this and be more appealing, and no more ghosts opening doors.
